language: node_js
node_js:
  - '10'
  - '8'
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
env:
  global:
  - secure: nPfcyxMqddIk11S0sx7UJCYiiycDJ85BpsbTGynqDwKgJQJVu8amPjgzyT4CQkaIyXK2LdjfRPvEYHmlpJz/rf+FKZME5HUbe+Dmb9PBkL+MdutEVcZpxAEj7Sm8oItYYQPGbDnTPVw1ueSkwFLj1oYpsUK7DZUfwNItGacK1Ahh87Gx5B8akvUXTYkwinXqyXJCF4ZSDNW/YWZzhEmDonapMVwvZES4GBQb1kX+8kzhdZGC6rOGirHwLNxdlT241FUv1L9fYlAwGnHMVVP7MQ4spH//TgGJLZCq8MpizszoLwn7gh+1iUFm5pSoy3V80t1nCdKHOw1SQinF6hCN5V/O0jLxLa//KuhEtgrMSycAdf0sbYPuZbZShWLXK2Cxf/90OuREoN3BPwchHPMGvkg3b++65NTeQh+vn+drkBOMcja5ahQEcIB6wjq7IVh/hnmj2pOsADCBoOmmK6NV/tEw3fj/5KZqA8YFIBVOt/UYiGvaL2qrhJgsMn0q5aPruVMgnwT1H7U6CIRzaq1jUmJAjaPtSVsFdbl1MTnMne/MfMNzYbpawbhdsZfJMMiBKhi+NebrPCYcayqFdlu3Ba9EHqvjWYOUmloWVtGEu9LilEIeq1ZSfDh1X5zutGZgnmG1LCx4DsuZe9Mvn4uk2eWD4BmFm7hv4AZ5sM/0d9w=
  - secure: qs/fALhfDrJNiZZzGMd8h4XGrO5utCMVIasEZhzEeIsskB6U/kcJO/E+mvwEp0x7/GR22k4Y7LoNmR57JmL6eOQpZKJYDVNDBN2lBbIIPhPFCHjL2zVpuzNGV2v1kBgE6d4w2lN4WW+IqEU5eWQhObTcJ6iujUU+ng9/ZTN3j6SJqREBe0r3WBxFPh2EBSzIfNEAnWEvbIe0tJbKKcLGdT6khreIRYfaY/m9S9DT9L8yH3Mv4usoz53It+uLlEo4G+4RbBuZZ9kbwEkh/oSJwa3MmH+C4Zl5f57Zlc76dea0Gq5F0ZxL91QoUNZ/Q8u/+1zP+n6w97FiSZtRhTojrncRg77pOShBNWYhC/fx1Uq3bMYYi5YQzhQn7f+zV5GnQBx59KwrJKBtJEqXVS5+op9+zB3KFrL9aY+q3F0C3uLYA9lfzsgQ/MMtND5p/QV9ViPJiHju8sGBPQ7tvHaE58UUUKoeszPSSuyb856tFjjQI67fGK5VRAwyuC1zp2d3XUqo6U5t0TsvwfnvTeDm5k0f8f0PYyZXc2ec8xwRbN1YcSwbN7lVlptAkM/IYaNwoIAKOlLcrqfzJ009xKy57SV+0HfwnxWOOE/IOwZzkLr1+wAGxQsT6SJBxkcK9m6YdFa1i6psb2ZQfbAbg/ku4+CXXUMaiPHffmQpKMmm8VE=

notifications:
  email: false
